name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          xcodebuild build \
            -scheme password-vault \
            -derivedDataPath build \
            -destination 'platform=iOS Simulator,name=iPhone 17'

      - name: Format
        run: |
          brew install swift-format
          swift-format lint --recursive --strict password-vault/
